# -*- coding: utf-8 -*-
"""DataViz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12e8Ld14T8CJooIlHPgsRzRnIdWFVsiA_

# **Visualização de Dados - Global Terrorism Database**

Esse trabalho visa validar hipóteses e apresentar insights baseados no [Global Terrorism Database](https://www.kaggle.com/START-UMD/gtd), uma base que apresenta informações sobre ataques terroristas dos anos de 1970 a 2017.
"""

!pip install --upgrade plotly
!pip install geopandas
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import missingno as msno
import plotly.express as px
import geopandas as gpd

from shapely.geometry import Point
from geopandas import GeoDataFrame
from wordcloud import WordCloud

df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding='ISO-8859-1')

"""Primeiramente, é importante validar quais colunas possuem dados faltantes, a fim de definir quais análises são possíveis sem a necessidade de tratamento dos dados, a fim de evitar a perda de veracidade dos dados como um todo."""

msno.bar(df, color="dodgerblue", sort="ascending")

"""O gráfico de barras acima nos mostra a quantidade de registros de cada coluna do dataset. Podemos observar que menos da metade das colunas do dataset estão preenchidas com mais de 80% de seus valores. No entanto, as análises desse trabalho serão focadas nessas colunas, visando resultados o mais próximo possível da realidade retratada pela base.

# **Número de ocorrências por ano**

Por se tratar de um dataset que reflete o terrorismo global do ano de 1970 ao ano de 2017, é interessante observamos em quais anos tivemos o maior e menor número de incidentes.
"""

df_to_lineplot = df.groupby('iyear').size()
frame = {'Ano': df_to_lineplot.index, 'Ocorrencias': df_to_lineplot.values}
df_to_lineplot = pd.DataFrame(frame)
sns.lineplot(data=df_to_lineplot, x='Ano', y='Ocorrencias').set(title='Número de ocorrências por ano')

"""Como podemos ver no gráfico de linha acima, o menor número de ocorrências foi registrado no ano de 1971, e em contrapartida o maior número foi registrado em 2014. Podemos ver também que do ano de 2010 ao ano de 2014 tivemos o maior crescimento desde o início dos registros disponibilizados no dataset. Por sua vez, a partir de 2014 os números caíram progressivamente, no entanto não alcançaram o nível do ano de 2010, continuando com um índice bem elevado de casos.

# **Número de ocorrências por mês**

Aprofundando um pouco mais nessa análise do número de ocorrências em determinado período de tempo, podemos validar se existe uma relação entre os incidentes e o mês em que ocorreram, visto que diversas variáveis podem influenciar como período de férias, festas, eleições, etc.
"""

imonth_txt = {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "May",
    "6": "Jun",
    "7": "Jul",
    "8": "Aug",
    "9": "Sep",
    "10": "Oct",
    "11": "Nov",
    "12": "Dec"
}
df["imonth_txt"] = pd.Series(
    df["imonth"].apply(lambda x: imonth_txt.get(str(x), "na")),
    dtype=pd.StringDtype(),
)
countplot = sns.countplot(x='imonth_txt', data=df, order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
countplot.set(xlabel='Mes', ylabel='Ocorrências', title='Número de ocorrências por mês')

"""Com essa análise, observamos que o maior número de ocorrências foi registrado no mês de Maio. Já o menor número, é referente ao mês de Dezembro, o que talvez possa ser associado as comemorações de fim de ano, onde muitas pessoas tiram folgas de seus trabalhos e se reúnem com suas famílias, reduzindo a possibilidade de novos casos de incidentes terroristas.

# **Ocorrências por região**

Quando se trata de problemas de segurança é sempre importante considerar a região onde os problemas acontecem. Regiões consideradas mais propícias ou com maior frequência de atentados terroristas acendem um alerta tanto para seus moradores, quanto para pessoas que estão passando por essas regiões independente de seus motivos.
"""

region = df['region_txt'].dropna()
region = region[:].str.replace(' ', '')
region = region[:].str.replace('&', '')
region = region[:].str.replace('-', '')

wordcloud = WordCloud(collocations=False).generate(' '.join(region.values))

plt.figure(figsize = (30,4))
plt.imshow(wordcloud, interpolation='bilinear',)
plt.axis("off")

"""Na nuvem de palavras acima são exibidas as regiões informadas no dataset, em ordem de quantidade de casos, da maior quantidade para a menor. Podemos observar que países do Oriente Médio e norte da África apresentam maior quantidade de incidentes, seguidos pelo sul da Ásia. Essas regiões estão sob constante tensão devido principalmente a conflitos políticos e religiosos, e as informações do dataset confirmam isso.

# **Distribuição de ocorrências pelo mundo**

Apesar de ter uma boa visibilidade sabendo as regiões que possuem mais ocorrências, nos casos de regiões muito grandes é interessante aprofundar mais nessa representação, para ter mais acertividade no momento de tomar decisões baseadas na quantidade de ataques terroristas por região.
"""

fig = px.scatter_geo(df, lat='latitude', lon='longitude')
fig.update_layout(title = 'Distribuição de ocorrências pelo mundo', title_x=0.5, width=1000, height=600)
fig.show()

"""# **Número de ataques por tipo**

Sabendo o número de incidentes, é importante saber qual o tipo de incidente ocorre com maior frequência. O dataset apresenta 9 tipos de incidentes, e vamos observar a seguir a quantidade de casos para cada tipo.
"""

sns.set(style='darkgrid')
histplot = sns.histplot(data=df, y='attacktype1_txt')
histplot.set_ylabel('Tipo de ataque')
histplot.set_xlabel('Quantidade')
histplot.set_title('Número de ataques por tipo')
plt.show()

"""O histograma acima nos mostra que o maior número de incidentes registrados pertence a categoria de bombardeios ou explosões, seguido por assalto armado com menos da metade do número de registros. Além disso, sequestro possui o menor número de incidentes entre as categorias apresentadas no dataset.

# **Número de ocorrências por tipo de arma**

Além dos tipos de incidentes, o dataset também apresenta o tipo de arma utilizada. Com isso, é possível detectar indícios de tráfico de armas de fogo ou explosivos, por exemplo.
"""

df_grouped = df.groupby(['weaptype1_txt']).size()
df_grouped.rename(index={'Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)': 'Vehicle'}, inplace=True)
scatterplot = sns.scatterplot(y=df_grouped.index.tolist(), x=df_grouped.values, size=df_grouped.values, legend=False, sizes=(50, 750))
scatterplot.set_title('Número de ocorrências por tipo de arma')
scatterplot.set_xlabel('Número de ocorrências')
scatterplot.set_ylabel('Tipo de arma')

"""Como podemos observar, os incidentes causados por explosivos e armas de fogo são expressivamente mais predominantes do que os demais tipos de armas. Essa informação pode justificar o início de investigações acerca do tráfico desses armamentos, visando descobrir como os criminosos conseguiram tais armas e com isso agindo para reduzir esses incidentes.

# **Quantidade de ocorrências que obtiveram sucesso por região e país**

Além de informar a região, o país e o tipo de incidente, o dataset também apresenta a conclusão da ocorrência, ou seja, se o crime obteve sucesso ou não. Essa informação é importante para avaliar a efetividade dos serviços de segurança e proteção do local onde o ataque foi feito.
"""

df_success = df[df['success'] == 1]
df_success = df
fig = px.treemap(df_success, path=[px.Constant('World'), 'region_txt', 'country_txt'], values='success')
fig.update_traces(root_color="lightgrey")
fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

"""No gráfico apresentado anteriormente, temos o número de ataques que obtiveram sucesso agrupados por região e país. Com isso, é possível saber por exemplo se dentro de uma mesma região, um país é muito mais perigoso que os outros, ou até mesmo se um conjunto de países geograficamente mais próximos dentro da mesma região possuem essa característica. Um caso que se encaixa nessa situação pode ser observado no sul da Ásia, que como podemos ver no gráfico possui número de sucesso de ataques muito próximo no Paquistão, Afeganistão e na Índia, sendo que o primeiro faz fronteira com os outros dois.

# **Correlação entre data do incidente, local, tipo e o sucesso do ataque**

Visto que já foram analisados isoladamente a data do incidente, a região e o tipo de ocorrência, podemos validar se existe correlação entre eles. Para isso, será utilizado o mapa de calor a seguir.
"""

corr = df[['iyear', 'imonth', 'iday', 'country', 'region', 'attacktype1', 'success']]
heatmap = sns.heatmap(corr.corr())
heatmap.set_title('Correlação entre data, local, tipo e sucesso')

"""Como podemos observar no mapa de calor acima, não existe uma correlação expressiva entre nenhuma das informações selecionadas para a construção do gráfico. Apesar disso, podemos ver que a correlação entre o ano em que a ocorrência foi registrada e a região possuem um coeficiente de aproximadamente 0.4, o que pode indicar em um primeiro momento que pode existir uma relação entre as duas variáveis em um dado período da amostra.

# **Distribuição dos incidentes por tipos de alvo**

Para setores de segurança pública/privada, é importante saber quais os tipos de alvos de incidentes registrados com maior frequência, para definir de forma mais efetiva investimentos e planejamento de ações.
"""

targtype = df.groupby('targtype1_txt').size().sort_values()
frame = {'type': targtype.index, 'size': targtype.values}
frame = pd.DataFrame(frame)
fig = px.pie(frame, values='size', names='type', color_discrete_sequence=px.colors.sequential.Inferno)
fig.update_layout(
    autosize=False,
    width=800,
    height=500,
    yaxis=dict(
        title_text="Y-axis Title",
        ticktext=["Very long label", "long label", "3", "label"],
        tickvals=[1, 2, 3, 4],
        tickmode="array",
        titlefont=dict(size=30),
    )
)
fig.show()

"""O gráfico anterior nos mostra a porcentagem de incidentes por tipo de alvo em relação ao total de registros presentes no dataset. Podemos observar que incidentes com foco em cidadãos e propriedades privadas representam 23,9% do total, o que possibilita que esse público alvo utilize essa informação para investir mais adequadamente em sua segurança e reduzir/evitar novos incidentes.

# **Conclusão**

A partir dos dados presentes no dataset, hipóteses foram levantadas e com o auxílio dos gráficos, puderam ser comprovadas ou negadas. Além disso, insights foram gerados e podem servir de motivação para trabalhos futuros.
"""